// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWClwrhShkkIOUMGuKIqNkSTBEcHiPnT8',
    appId: '1:361090128531:android:79475596b3711292d20b66',
    messagingSenderId: '361090128531',
    projectId: 'financeiro-aba8a',
    databaseURL: 'https://financeiro-aba8a-default-rtdb.firebaseio.com',
    storageBucket: 'financeiro-aba8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA51bxJoRlGxZRLOPLqxT1jAN0PgQ_-Bk',
    appId: '1:361090128531:ios:664b340e549f836dd20b66',
    messagingSenderId: '361090128531',
    projectId: 'financeiro-aba8a',
    databaseURL: 'https://financeiro-aba8a-default-rtdb.firebaseio.com',
    storageBucket: 'financeiro-aba8a.appspot.com',
    iosClientId: '361090128531-f77ve24rs64ied2jsnpbm9r3nbt0eatq.apps.googleusercontent.com',
    iosBundleId: 'com.vinicius.financeiro.financeiro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA51bxJoRlGxZRLOPLqxT1jAN0PgQ_-Bk',
    appId: '1:361090128531:ios:664b340e549f836dd20b66',
    messagingSenderId: '361090128531',
    projectId: 'financeiro-aba8a',
    databaseURL: 'https://financeiro-aba8a-default-rtdb.firebaseio.com',
    storageBucket: 'financeiro-aba8a.appspot.com',
    iosClientId: '361090128531-f77ve24rs64ied2jsnpbm9r3nbt0eatq.apps.googleusercontent.com',
    iosBundleId: 'com.vinicius.financeiro.financeiro',
  );
}
